apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapptemplatedeployment
  labels:
    version: ${version}
    app: dotnet-webapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        version: ${version}
        app: dotnet-webapp
    spec:
      containers:
      - name: webapptemplate
        image: ${containerImage}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: webapptemplate-config
        readinessProbe:
          httpGet:
            path: /monitoring/readiness
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /monitoring/health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 3
      imagePullSecrets:
        - name: azurecontainerreg
