apiVersion: v1
kind: Service
metadata:
  name: dotnet-webapptemplate
  labels:
    app: dotnet-webapp
spec:
  selector:
    app: dotnet-webapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP