apiVersion: v1
kind: Service
metadata:
  name: dotnet_webapptemplate
  labels:
    app: dotnet_webapp
spec:
  selector:
    app: dotnet_webapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP